"""
DN CLASSIC — Upstream Types & Data Contracts
Represents read-only source inputs, analysis snapshots, structure records,
agent proposal protocols, guard results, and pipeline execution results.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Any, Iterator
from contracts import (
    SemanticMode,
    LifecycleStatus,
    GroundingStatus,
    EpistemicUncertainty,
    SourceSpan,
    TemporalAttributes,
    IdentifiedOntology,
    LifecycleCandidate,
    OutputContract,
    EvidencePackage,
    GateDecision,
)
from source_boundary import SourceDocument


@dataclass(frozen=True)
class ReadOnlySource:
    """Immutable read-only representation of a single source document."""
    source_id: str
    raw_bytes: bytes
    text_content: str
    sha256_hash: str


@dataclass(frozen=True)
class AnalysisSnapshot:
    """Deterministic snapshot of an entire archive or document collection."""
    snapshot_id: str
    sources: Dict[str, ReadOnlySource]
    total_bytes: int
    computed_hash: str


@dataclass(frozen=True)
class StructureRecord:
    """Structured document material presented to the agent proposer."""
    document_id: str
    text: str
    normalized_text: str
    source_hash: str
    metadata: Dict[str, Any] = field(default_factory=dict)


class GuardStatus(str, Enum):
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    UNKNOWN = "UNKNOWN"


class ContentNature(str, Enum):
    """
    Classification of source material nature (Code-as-Data invariant).
    Documents may contain arbitrary executable code, scripts, or directives,
    which remain strictly passive observation data without execution capability.
    """
    NATURAL_TEXT = "NATURAL_TEXT"
    CODE_OR_EXECUTABLE = "CODE_OR_EXECUTABLE"
    CONFIG_OR_STRUCTURED = "CONFIG_OR_STRUCTURED"
    ENCODED_DATA = "ENCODED_DATA"
    PSEUDO_SYSTEM_DIRECTIVE = "PSEUDO_SYSTEM_DIRECTIVE"


@dataclass(frozen=True)
class AgentProposal:
    """Proposal generated by an external agent for validation and assembly."""
    document_id: str
    target_entity_id: Optional[str] = None
    semantic_mode: SemanticMode = SemanticMode.CLAIM
    lifecycle_status: LifecycleStatus = LifecycleStatus.ACTIVE
    grounding_status: GroundingStatus = GroundingStatus.GROUNDED_SOURCE_CLAIM
    epistemic_uncertainty: EpistemicUncertainty = EpistemicUncertainty.CLEAR
    source_spans: List[SourceSpan] = field(default_factory=list)
    temporal: Optional[TemporalAttributes] = None
    candidate_evidence_refs: List[str] = field(default_factory=list)
    domain_facts: Optional[Dict[str, str]] = None
    identified_ontology: Optional[IdentifiedOntology] = None
    is_command: bool = False  # If True, Guard will immediately reject
    content_nature: ContentNature = ContentNature.NATURAL_TEXT


@dataclass(frozen=True)
class GuardValidationResult:
    status: GuardStatus
    reason: str
    verified_spans: List[SourceSpan] = field(default_factory=list)


@dataclass(frozen=True)
class ProposalSet:
    """Collection of proposals generated by the agent."""
    proposals: List[AgentProposal] = field(default_factory=list)
    agent_id: Optional[str] = None
    timestamp_utc: Optional[str] = None


@dataclass(frozen=True)
class GuardedProposal:
    proposal: AgentProposal
    validation: GuardValidationResult


@dataclass(frozen=True)
class PipelineExecutionResult:
    """
    Complete traceable result of an end-to-end pipeline run.
    Implements container interfaces for transparent backward compatibility.
    """
    snapshot: AnalysisSnapshot
    structure_records: List[StructureRecord]
    proposals: ProposalSet
    guarded_proposals: List[GuardedProposal]
    candidates: List[LifecycleCandidate]
    output_contracts: List[OutputContract]
    evidence_packages: List[EvidencePackage]
    dle_receipts: List[Any]

    @property
    def source_documents(self) -> List[SourceDocument]:
        return [
            SourceDocument(document_id=r.document_id, text=r.normalized_text)
            for r in self.structure_records
        ]

    def __iter__(self) -> Iterator[SourceDocument]:
        return iter(self.source_documents)

    def __len__(self) -> int:
        return len(self.structure_records)

    def __getitem__(self, index: int) -> SourceDocument:
        return self.source_documents[index]
